### ISSUE TITLE
Раздел для скачивания 

### ISSUE THREAD

**Issue by eSlider** [c-pay/currency#5]
Раздел для скачивания приложений cPay на http://cpay.click/dist

**Comment by AntonioBD** [comment]
@eSlider 
в коде Даш он ссылается на папку download. 
может так же ее создать, что бы в коде не менять на distr ?

**Comment by AntonioBD** [comment]
давай этот ишью закроем что бы не путаться, я в общие его перенес ?
все равно нужно правильнее учитывать общий список проблем для всех валют и и его потом при каждом форме видеть и заранее предусматривать

**Comment by eSlider** [comment]
>в коде Даш он ссылается на папку download.
>может так же ее создать, что бы в коде не менять на distr ?

Сайт дэша - это не проект дэша, можно и download. 

> давай этот ишью закроем что бы не путаться, я в общие его перенес ?
> все равно нужно правильнее учитывать общий список проблем для всех валют и и его потом при > каждом форме видеть и заранее предусматривать

Список  issues и есть список проблем, которые предстоит решить перед запуском.

 @AntonioBD

**Comment by AntonioBD** [comment]
@eSlider то есть создашь папку download на сайте cpay и там разместим дистрибутивы для закачки ?
удалю этот ишьюс, так как этот пункт есть в полном ишьюс списке, что бы не путаться них ?)

**Comment by AntonioBD** [comment]
@eSlider  я не очень понял может что такое Требуется помощь отметка, но папку Download в cpay.click на хостинге создал )

**Comment by eSlider** [comment]
Всё ок. Скачать кошельки можно с https://cpay.click
