### ISSUE TITLE
первичный запуск на win32. необходимые доработки:

### ISSUE THREAD

**Issue by AntonioBD** [c-pay/currency#7]
1.  [x] иконка приложения инсталятора  
![icon](https://user-images.githubusercontent.com/32811115/39429331-72f46ec6-4c82-11e8-8386-d8e2a2917315.png)
2. [x] ярлык приложения после интсаляци (и его инконка?)
- [x] картинка ярлыка нужна как на инсталяторе красивая
3. [x] Расработчкики -2017 Dash,  2018 сРау (в загрузочной картинке инсталяции)
![ice_screenshot_20180430-133957](https://user-images.githubusercontent.com/32811115/39429336-77b243ca-4c82-11e8-9373-38da971ac58e.jpeg)

6. [x] лого сРау сверхуслева в приложении - на белый фон
7. [x] лого обзор - заменим на сРау - непонятно какой  файл он берет для этого что бы его заменить
8. [x] лого Срау длинное над Недавние транзакции - некрасивое, переделаем. надо понять какой файл это
- [x] лого Срау длинное над Недавние транзакции  еще раз надо перезалить на центровку лого справа, а не слева

![ice_screenshot_20180430-142026](https://user-images.githubusercontent.com/32811115/39429287-5430c200-4c82-11e8-9804-d14249c5a984.jpeg) (для п. 6,7,8

5. [x] скорость майнига бешенная. надо еще раз в 10 уменьшить даже те что компом майнятся
9. [x] настройка Ноды (НОД)
10. [x] получение доступа к премайнинговым моентам
11. [x] настройка нескольких кошельков на одном компьютере
12. [x] отключение майнинга POW (остается только майнинг при самих транзакциях - fee)

**Comment by eSlider** [comment]
@AntonioBD, давай здесь оствим визуальные задачи, а скорость майнинга и прочие настройки продолжим в #4 

@eSlider  давай тут будем описывать то, что всплыло после запуска. по мере решения вопросов будем там тоже править, но тут будет архив важных "вскрытых" задач

**Comment by eSlider** [comment]
@AntonioBD, может привлечь сюда Марка или кто ещё занимается дизайном?
 @eSlider  это долго. я сам подправлю значки. Марк пусть сайт наконец закончит, у него все время там важно
надо понять какие файлы заменять, а сами картинки я сделаю без проблем
